### ISSUE TITLE
Weird internal registry use

### ISSUE THREAD

**Issue by OutdatedVersion** [Remitly/verdaccio-s3-storage#12]
This package is using an internal registry for the AWS SDK; which is a bit suspicious. What is the reasoning behind this?

https://github.com/Remitly/verdaccio-s3-storage/blob/master/yarn.lock#L443

**Comment by soulchild** [comment]
Given that the `yarn.lock` file is excluded via [.npmignore](https://github.com/Remitly/verdaccio-s3-storage/blob/master/.npmignore#L7) from any official releases to the npm registry, this should not be a problem. 
But this makes it hard/impossible to contribute to the project if you want to use yarn, because you'll be unable to install the `aws-sdk` dependency from their internal registry. npm should work, given there's no `package-lock.json` with a similar "twist". Would be interesting to know, what the differences between those two versions are, though ...

**Comment by apexskier** [comment]
This is a mistake, I'll address!

**Comment by apexskier** [comment]
Closed by c45a38ac8d2b2d43a85c21c509466f265a8ac70b, v0.1.1 will have the fix.
